### ISSUE TITLE
Agregar campo para incluir las fuetes reales del contenido

### ISSUE THREAD

**Issue by jashk** [RZEROSTERN/banfakenews#2]
Es importante que además de poder reportar una noticia falsa podamos incluir enlaces o información que la desmiente o la pone fuera de contexto.

**Comment by RZEROSTERN** [comment]
Agregada en el commit e1e0de4
https://github.com/RZEROSTERN/banfakenews/commit/e1e0de4264ed7fbbcbb6fd53be0aedf8ed8dfc5f

Gracias
