### ISSUE TITLE
Permitir Login con Redes Sociales

### ISSUE THREAD

**Issue by rxco** [RZEROSTERN/banfakenews#3]
Para pemitir carga de reportes de manera mas rápida y reducir el mal uso de la plataforma por usuarios mal intencionados.

**Comment by RZEROSTERN** [comment]
Suena bien, en desarrollo.

**Comment by yagarasu** [comment]
Si ya está alguien trabajando en ello, lo mejor es pasar el issue a in progress o algo así para que no se trabaje doble

**Comment by RZEROSTERN** [comment]
Pueden probar en https://banfakenews.sandbox.rzerocorp.com ??? Registro y Login vía Facebook

**Comment by RZEROSTERN** [comment]
Fixed, cierro issue
