### ISSUE TITLE
Corroborar pedidos de ayuda

### ISSUE THREAD

**Issue by jupazave** [RZEROSTERN/banfakenews#4]
Revisar si un pedido de ayuda es vigente o ya no, para que no se duplique la ayuda en los lugares.

**Comment by RZEROSTERN** [comment]
Se puede agregar un módulo referente a ello, sin embargo siento que ya está este requerimiento subsanado en https://github.com/erikcaffrey/AyudaMexico. ¿Crees que pueda ayudarte ese proyecto? 

Saludos, espero tu respuesta.
