### ISSUE TITLE
Agregar Botón para Confirmar Fake News.

### ISSUE THREAD

**Issue by rxco** [RZEROSTERN/banfakenews#5]
Permitir que otros usuarios con un botón confirmen que la noticia es falsa y aumenten el porcentaje de fiabilidad.

**Comment by RZEROSTERN** [comment]
¿Más o menos como una especie de voting?

**Comment by yagarasu** [comment]
Yo también creo que es necesario un tipo de voting para arriba o para abajo, así los reportes falsos de reportes falsos pueden ser refutados de alguna forma.

**Comment by RZEROSTERN** [comment]
Perfecto, igualmente siéntanse libres de hacer fork y hacer la issue. No hay ningún problema.

**Comment by 0nix** [comment]
+1

**Comment by RZEROSTERN** [comment]
Solucionado en #12. Gracias @jluispuc
