### ISSUE TITLE
Hacer lista de noticias falsas publica

### ISSUE THREAD

**Issue by 0nix** [RZEROSTERN/banfakenews#7]
El listado de noticias solo esta disponible para personas que hicieron login. Por favor hacer vista de noticas publica que no sean editables.

**Comment by agush22** [comment]
+1
No le veo utilidad al sitio si necesariamente hay que loggearse

**Comment by jluispuc** [comment]
Miré antes que se tendrían que loggear con las redes sociales, pienso que este listado debería poder ser compartido si piden que solo lo vean los que hicieron login.

**Comment by RZEROSTERN** [comment]
Ya está pública la lista. Gracias a todos.

**Comment by RZEROSTERN** [comment]
@jluispuc ¿crees que puedas trabajar en el share? Pasa al canal de Slack para más detalles, mientras te asigno la issue

**Comment by jluispuc** [comment]
@RZEROSTERN claro, veremos que se puede hacer, indiqueme por favor cual es el canal

**Comment by RZEROSTERN** [comment]
https://codeandomexico.slack.com en el canal #sismomx-fakenews

**Comment by Garyi** [comment]
Al igual que dice @agush22  No creo que tenga que ser necesario logearse

**Comment by RZEROSTERN** [comment]
Ya fue subsanado ese detalle @Garyi, @jluispuc cierro esta issue, puedes abrir una con los detalles de Sharing ???
