### ISSUE TITLE
API that Feeds into Bot

### ISSUE THREAD

**Issue by saiphcita** [RZEROSTERN/banfakenews#8]
We need an API that basically generates a JSON file with information about the fake news stories. This JSON file will be read by a bot to share on social media and give visibility to the potential fake news story. We want people who were exposed to the fake news story to be aware that it could unreal.

**Comment by RZEROSTERN** [comment]
In development

**Comment by RZEROSTERN** [comment]
Postman for API endpoints (sandbox) https://www.getpostman.com/collections/a99cfa135db7b37e0f05

**Comment by RZEROSTERN** [comment]
Postman for API endpoints (production) https://www.getpostman.com/collections/d8ccece0a2238930e55a
